name: Code quality check

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
    branches:
      - example/* # INFO: Used in the template
      - feature/*
  pull_request:
    branches:
      - main
      - develop

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  code-quality-check:
    name: Code quality check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint TypeScript
        run: pnpm lint:types
      - name: Lint ESLint
        run: pnpm lint:all
      - name: Test
        run: pnpm test:cov
